name: example
description: Analytics example.
publish_to: none
version: 1.0.0+1

dependencies:
  analytics:
    path: ../
  appmetrica_plugin: ^1.4.0
  firebase_analytics: ^8.3.4
  firebase_analytics_web: ^0.3.0+1
  firebase_core: ^1.8.0
  firebase_core_web: ^1.6.5
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  surf_lint_rules: ^3.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
  uses-material-design: true
