name: example
description: Analytics example.
publish_to: none
version: 1.0.0+1

dependencies:
  analytics:
    path: ../
  firebase_analytics: ^8.3.4
  firebase_core: ^1.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  surf_lint_rules: ^2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
  uses-material-design: true
