name: analytics
version: 2.0.2
description: Interface for working with analytic services. The library is supposed to unify work with various analytic services.
repository: "https://github.com/surfstudio/flutter-analytics"
issue_tracker: "https://github.com/surfstudio/flutter-analytics/issues"

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  logger: ^1.0.0

dev_dependencies:
  mocktail: ^0.1.0
  surf_lint_rules: ^3.0.0
  test: ^1.17.2
