name: "Build package example"

on:
  pull_request:
    branches:
      - main 
    
  # workflow_run:
    # workflows: ["/Analysis"]
    # types: [completed]

jobs:
  build_android_example:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
        # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name: Android NDK toolchain Setup
      uses: ravinderjangra/android-ndk-toolchain-setup@0.1
      with: 
        api: '21'
        arch: 'arm'
        install-location: 'toolchains'

    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: "stable"

    - name: Install dependencies
      run: flutter pub get

    - name: Build Android
      run: |
        cd example
        flutter pub get
        flutter build apk
  
  build_ios_example:
    runs-on: macos-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: |
          cd example
          flutter pub get
          flutter build ios --release --no-codesign

