name: "Run Testing"

on:
  workflow_run:
    workflows: ["Analysis"]
    types:
      - completed

jobs:
  testing:
    runs-on: ubuntu-latest

    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests 
        run: flutter test
