name: "Analysis"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Install Flutter 
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies 
        run: flutter pub get

      - name: Run dependency validator 
        run: |
          dart pub global activate dependency_validator
          dart pub global run dependency_validator:dependency_validator
      - name: Run analyzer 
        run: flutter analyze --fatal-warnings --fatal-infos .

      - name: Run formatter 
        run: flutter format --set-exit-if-changed .

      - name: Run package analyzer 
        uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  testing:
    needs: analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Install Flutter 
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies 
        run: flutter pub get

      - name: Run tests 
        run: flutter test
  
  build_android_example:
    needs: analysis
    runs-on: ubuntu-latest
    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android
        run: |
          cd example
          flutter pub get
          flutter build apk

  build_ios_example:
    needs: analysis
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: |
          cd example
          flutter pub get
          flutter build ios --release --no-codesign
